services:
  db:
    image: postgres:15
    restart: unless-stopped
    ports: ["5432:5432"]
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: grapes_saas
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: unless-stopped
    ports: ["8080:8080"]
volumes:
  pgdata: {}
